version: '3.8'

services:
  webshop-app:
    build:
      context: ./main_app
    ports:
      - "3000:3000"
    volumes:
      - ./user_session_logs:/app/user_session_logs 
      - ./data:/app/data
    environment:
      DATASET_SOURCE: "small" # Could be small | all

  log-observer:
    build:
      context: ./observer_service
    volumes:
      - ./user_session_logs:/observer/user_session_logs
    environment:
      INTERNAL_URL: "http://webshop-app:3000"
      EXTERNAL_ACCESS_URL: "https://webshop.nfig.ai"
      NFIG_API_KEY: ${NFIG_API_KEY}
    ports:
      - "5000:5000"
    depends_on:
      - webshop-app
